from sources.GraphExplReport import *
from sources.QueryProcess import *
from sources.Explproc import *
from sources.PdfForm import *


def run_explain_query_plan(dba):
    edp = ExplDbproc(dba.qid, dba.rpath)
    qp = QueryProcess(dba.conn)
    eqrdata = qp.run_sql_script(
        prefix='EXPLAIN QUERY PLAN ', sql_in=dba.qfile, fetch_flag='many')
    fdata = [
        f'"{i+1}","{eqrdata[i][0]}","{eqrdata[i][1]}","{eqrdata[i][2]}","{eqrdata[i][3]}"\n' for i in (range(len(eqrdata)))]
    fdata = [f'"step","id","parent","unused","detail"\n']+fdata
    qp.write_file_txt(fdata=list(fdata),
                      fname=edp.exp_repfile, line_update='not')
    ger = GraphExplReport(data=eqrdata)
    qp.write_file_txt(fdata=list(ger.exp_graphrepfile_data),
                      fname=edp.exp_graphrepfile, line_update='not')

    # compose EXPLAIN QUERY PLAN REPORT in PDF format
    title = f"EXPLAIN QUERY PLAN REPORT on {(dba.qfile[dba.qfile.find(dba.qid):]).strip('_query.sql')} "

    # portrait / milimeters / A4 size Note: A4 page width/height - 210:297
    pdf = PDF('P', 'pt', 'A4')
    pdf.compress = True
    pdf.alias_nb_pages()
    pdf.doc_title(title)
    # pdf.page_no.__init__()
    pdf.add_page()
    pdf.insert_toc_placeholder(render_toc)
    pf = PdfForm
    pdf.start_section(
        f"1. SQL statement {dba.qfile[dba.qfile.find(dba.qid):]}", level=0, strict=True)
    pf(pdf, unit_name=dba.qfile, unit_id='er_txt').form_section()
    pdf.add_page()
    pdf.start_section(
        f"2. Explain query plan generated by <EXPLAINE QUERY PLAN sql_statement> ", level=0,)
    pdf.start_section(f"2.1. Plain report", level=1, strict=True)
    pf(pdf, unit_name=edp.exp_repfile, unit_id='er_txt').form_table()
    qp.delete_file(edp.exp_repfile)
    pdf.add_page(orientation='landscape')
    pdf.start_section(f"2.2. GRAPH report", level=1, strict=True)
    pf(pdf, unit_name=edp.exp_graphrepfile, unit_id='graph').form_section()
    qp.delete_file(edp.exp_graphrepfile)
    pf(pdf, unit_name=edp.exp_repfile_pdf).print_report()
